"""HydroSight TN source package."""

from .config import (
    AHP_FACTORS,
    AHP_PAIRWISE_MATRIX,
    CLASS_COLORS,
    CLASS_LABELS,
    FEATURE_ORDER,
    NODATA_FLOAT,
    NODATA_UINT8,
    RECOMMENDATIONS,
    STUDY_BOUNDS_WGS84,
    TARGET_CRS,
    TARGET_RESOLUTION,
)

__all__ = [
    "AHP_FACTORS",
    "AHP_PAIRWISE_MATRIX",
    "CLASS_COLORS",
    "CLASS_LABELS",
    "FEATURE_ORDER",
    "NODATA_FLOAT",
    "NODATA_UINT8",
    "RECOMMENDATIONS",
    "STUDY_BOUNDS_WGS84",
    "TARGET_CRS",
    "TARGET_RESOLUTION",
]
